# Generated by Django 5.2.5 on 2025-09-05 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deparmaent',
            new_name='Department',
        ),
    ]
