# Generated by Django 5.2.5 on 2025-09-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='abrev',
        ),
    ]
