# Generated by Django 5.2.5 on 2025-09-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_country_abrev'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='abrev',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
