# Generated by Django 5.2.5 on 2025-10-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
